version: '3'
services:
  app:
    image: app:latest
    command: bash /code/scripts/run-prod.sh
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

